name: archlinux
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm docker curl p7zip git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory ${{ github.workspace }}

      - name: Setup llvm-clang-x86_64_v3 Toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm-clang-latest-ucrt-x86_64_v3.7z
          7z x llvm*.7z
          rm llvm*.7z
      - name: 获取 GCC 预定义宏
        run: |
          echo "显示github.workspace"
          echo "${{ github.workspace }}"
          echo "显示当前路径"
          pwd
          echo "x86_64-w64-mingw32-gcc的完整路径"
          realpath cross/bin/x86_64-w64-mingw32-gcc
          echo "获取 GCC 预定义宏"
          cross/bin/x86_64-w64-mingw32-gcc -dM -E - -march=x86-64-v3

      - name: list all users
        run: |
          echo "列出所有用户============"
          cat /etc/passwd | cut -d: -f1
          echo "显示当前用户名==========="
          whoami
          echo "显示系统级makepkg.conf=============="
          cat /etc/makepkg.conf
          echo "makepkg=============="
          which makepkg
      - name: working directory without checkout
        run: |
          echo "显示当前路径=============="
          pwd
          mkdir dir-sysusers
          sudo cp -r /usr/lib/sysusers.d/* dir-sysusers
          7z a dir-sysusers.7z dir-sysusers

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dir-sysusers.7z
          tag: dev
          overwrite: true
          file_glob: true
          
      - name: Checkout
        run: |
          git clone https://github.com/eko5624/test
          cd test
          pwd
          
      - name: working directory
        run: |
          echo "显示当前路径=============="
          pwd
          echo "显示变量github.workspace路径==============="
          echo "${{ github.workspace }}"
          echo "cmake================="
          which cmake
      
      - name: github path
        run: |
          echo "显示路径变量=============="
          echo "$PATH"
          echo "/usr=============="
          find /usr/local/ .
          echo "github home============="
          cd ~
          pwd
          find .
          echo "list /github=========="
          find /github
          echo "github workspace env============="
          echo "${{ github.workspace }}"

          
