name: archlinux
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest      
    steps:
      - name: pkgconf
        run: |
          pkgconf -version
          which pkgconf
      - name: 获取 CLANG march
        run: |
          echo "显示github.workspace"
          echo "${{ github.workspace }}"
          echo "显示当前路径"
          pwd
          echo "x86_64-w64-mingw32-gcc的完整路径"
          realpath clang-v3/bin/x86_64-w64-mingw32-gcc
          echo "判断clang-x86_64-v3预定义宏是否包含AVX"
          if echo | /__w/test/test/clang-v3/bin/x86_64-w64-mingw32-gcc -dM -E - -march=x86-64 | grep -q "__AVX"; then
            echo "$?"
            echo "GCC_ARCH_HAS_AVX"
          fi
          echo "获取clang-x86_64预定义宏"
          /__w/test/test/clang/bin/x86_64-w64-mingw32-gcc -dM -E - -march=x86-64
          echo "判断clang-x86_64预定义宏是否包含AVX"
          if echo | /__w/test/test/clang/bin/x86_64-w64-mingw32-gcc -dM -E - | grep -q "__AVX"; then
            echo  "$?"
          fi

      - name: 获取 GCC march
        run: |
          echo "显示github.workspace"
          echo "${{ github.workspace }}"
          echo "显示当前路径"
          pwd
          echo "x86_64-w64-mingw32-gcc的完整路径"
          realpath gcc-v3/bin/x86_64-w64-mingw32-gcc
          echo "获取gcc-x86_64-v3预定义宏"
          /__w/test/test/gcc-v3/bin/x86_64-w64-mingw32-gcc -dM -E - -march=x86-64
          echo "获取gcc-x86_64预定义宏"
          /__w/test/test/gcc/bin/x86_64-w64-mingw32-gcc -dM -E - -march=x86-64
          echo "显示x86_64-w64-mingw32-gcc -v"
          /__w/test/test/gcc-v3/bin/x86_64-w64-mingw32-gcc -v          
          
      - name: list all users
        run: |
          echo "列出所有用户============"
          cat /etc/passwd | cut -d: -f1
          echo "显示当前用户名==========="
          whoami
          echo "显示系统级makepkg.conf=============="
          cat /etc/makepkg.conf
          echo "makepkg=============="
          which makepkg
      - name: working directory without checkout
        run: |
          echo "显示当前路径=============="
          pwd
          mkdir dir-sysusers
          sudo cp -r /usr/lib/sysusers.d/* dir-sysusers
          7z a dir-sysusers.7z dir-sysusers

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dir-sysusers.7z
          tag: dev
          overwrite: true
          file_glob: true
          
      - name: Checkout
        run: |
          git clone https://github.com/eko5624/test
          cd test
          pwd
          
      - name: working directory
        run: |
          echo "显示当前路径=============="
          pwd
          echo "显示变量github.workspace路径==============="
          echo "${{ github.workspace }}"
          echo "cmake================="
          which cmake
      
      - name: github path
        run: |
          echo "显示路径变量=============="
          echo "$PATH"
          echo "/usr=============="
          find /usr/local/ .
          echo "github home============="
          cd ~
          pwd
          find .
          echo "list /github=========="
          find /github
          echo "github workspace env============="
          echo "${{ github.workspace }}"

          
