name: luajit

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install Homebrew packages
      run: |
        brew update
        brew install automake libtool llvm

    - name: Set environment variables for Clang/LLVM
      run: |
        echo "CC=/usr/local/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/local/opt/llvm/bin/clang++" >> $GITHUB_ENV
        echo "LDFLAGS=-fuse-ld=lld -L/usr/local/opt/llvm/lib/c++ -Wl,-rpath,/usr/local/opt/llvm/lib/c++" >> $GITHUB_ENV
        echo "PATH=/usr/local/opt/llvm/bin:$PATH" >> $GITHUB_ENV
        echo "CPATH=/usr/local/include:$CPATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "nproc=$(sysctl -n hw.logicalcpu)" >> $GITHUB_ENV

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python packages
      run: |
        python -m pip install -U pip
        pip install -U cython setuptools wheel

    - name: Print python version
      run: |
        which python
