name: arm-mpv

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Test mpv
      run: |
        curl -OL https://github.com/eko5624/mpv-mac/releases/download/2024-07-25/mpv-arm64-git-cb75ecf19f.zip
        unzip mpv*.zip
        ./mpv/mpv.app/Contents/MacOS/mpv
