name: luajit

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Test mpv
      run: |
        brew list
