name: brew

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-12
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1 
    steps:   
    - name: test
      run: |       
        set -x
        brew update
        brew cleanup

        # Remove stray upstream python binary symlinks under /usr/local
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
        brew unlink python && brew link --overwrite python

        mpv_deps=(
          python@3.10 
          python@3.11 
          ninja 
          meson 
          brotli
          glslang 
          jpeg-turbo
          libass 
          libarchive 
          little-cms2 
          luajit 
          mujs 
          uchardet 
          vapoursynth
        )

        ffmpeg_deps=(
          dav1d
          fontconfig
          freetype
          frei0r
          gnutls
          lame
          libbluray
          libbs2b
          libcaca
          libmodplug
          librist
          libsoxr
          libssh
          libvidstab
          libvorbis
          libvpx
          opencore-amr
          openjpeg
          openssl@1.1
          opus
          rav1e
          rubberband
          sdl2
          snappy
          speex
          srt
          tesseract
          theora
          webp
          xvid
          xz
          zeromq
          zimg            
        )

        deps=("${mpv_deps[@]}" "${ffmpeg_deps[@]}")        
        required_deps=($(brew deps -n --union "${deps[@]}"))          
        all_deps=("${deps[@]}" "${required_deps[@]}")
        sys_deps=($(brew list))
        
        IFS=$'\n'; set -f
        intersection=($(comm -12 <(
        printf '%s\n' "${all_deps[@]}" | sort) <(
        printf '%s\n' "${sys_deps[@]}" | sort)))

        exclude_lst=("autoconf")
        for index in "${!intersection[@]}"; do
          for exclude in "${exclude_lst[@]}"; do
            if [[ ${intersection[$index]} == $exclude ]]; then
            unset 'intersection[index]'
            fi
          done
        done
        brew uninstall --ignore-dependencies "${intersection[@]}"
        brew install -s pkg-config
        brew install -s "${required_deps[@]}"
        brew install -s "${deps[@]}"

