name: brew-get-ver

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-13
    steps:   
    - name: test
      run: |       
        #brew update && brew info zlib | grep "zlib:" | awk '{print $4}'
        #ver=$(brew info zlib | grep -E "zlib:" | cut -f4)
        #echo "$ver"
        brew info zlib | grep '==>'
        #brew info zlib

        
