name: brew-get-ver

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-13
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1 
    steps:   
    - name: test
      run: |       
        brew update && brew info zlib
        ver=`brew update && brew info zlib | grep "zlib:" | awk '{print $4}'`
        echo "$ver"
