name: brew

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-12
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1 
    steps:   
    - name: test
      run: |       
        set -x
        mpv_deps=(
          python@3.10 
          python@3.11 
          ninja 
          meson 
          brotli
          glslang 
          jpeg-turbo
          libass 
          libarchive 
          little-cms2 
          luajit 
          mujs 
          uchardet 
          vapoursynth
        )

        ffmpeg_deps=(
          dav1d
          fontconfig
          freetype
          frei0r
          gnutls
          lame
          libbluray
          libbs2b
          libcaca
          libmodplug
          librist
          libsoxr
          libssh
          libvidstab
          libvorbis
          libvpx
          opencore-amr
          openjpeg
          openssl@1.1
          opus
          rav1e
          rubberband
          sdl2
          snappy
          speex
          srt
          tesseract
          theora
          webp
          xvid
          xz
          zeromq
          zimg            
        )
        all_deps=($(brew deps -n --union --include-build --include-test "${mpv_deps[@]}" "${ffmpeg_deps[@]}"))     
        sys_deps=($(brew list))
        
        intersection=()
        for all in "${all_deps[@]}"; do
          for sys in "${sys_deps[@]}"; do
            if [[ $all == $sys ]]; then
              intersection+=("$all")
            fi
          done
        done

        for inter_dep in "${intersection[@]}"; do
          brew uninstall --ignore-dependencies $inter_dep;
        done
        brew install "${all_deps[@]}"
