name: brew-get-ver

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-13
    steps:   
    - name: test
      run: |       
        brew update
        brew info zlib | grep '==> zlib'

        
