name: brew

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-12
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1 
    steps:   
    - name: test
      run: |       
        set -x
        mpv_deps=(
          libass
          vapoursynth
        )

        ffmpeg_deps=(
          dav1d
          fontconfig
          freetype
          frei0r            
        )
        all_deps=$(brew deps -n --union --include-build --include-test "${mpv_deps[@]}" "${ffmpeg_deps[@]}")     
        sys_deps=$(brew list)
        
        IFS=$'\n'; set -f
        intersection=$(comm -12 <(
        printf '%s\n' "${all_deps[@]}" | sort) <(
        printf '%s\n' "${sys_deps[@]}" | sort))
        brew uninstall "${intersection[@]}" --ignore-dependencies

        brew install "${all_deps[@]}" --ignore-dependencies
        brew install "${mpv_deps[@]}" "${ffmpeg_deps[@]}"
