name: check-sdk

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-11
    env:
      SDKROOT: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"    
      MACOS_SDK: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SDK_PATH: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"    
    steps: 
    - name: Switch to MacOSX 10.15 SDK
      id: macossdk
      run: |
        curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.15.sdk.tar.xz
        tar -C $SDK_PATH -xf MacOSX10.15.sdk.tar.xz
        sudo rm -rf $SDK_PATH/MacOSX11.3.sdk
        sudo mv $SDK_PATH/MacOSX.sdk $SDK_PATH/MacOSX11.3.sdk
        sudo ln -s $SDK_PATH/MacOSX10.15.sdk $SDK_PATH/MacOSX.sdk
        sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.15" /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist
   
    - name: Switch to Xcode 12.5.1
      id: xcode1251
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer   
   
    - name: Check
      run: |
        echo "CommandLineTools sdks===="
        ls /Library/Developer/CommandLineTools/SDKs
        echo "show sdk version"
        xcrun --show-sdk-version
        echo "find swift===="
        sudo xcrun --toolchain swift --find swift
        echo "toolchain swift version===="
        sudo xcrun --toolchain swift swift --version        
        
