name: check-sdk

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-10.15
    #env:
      #SDKROOT: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"    
      #MACOS_SDK: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      #SDK_PATH: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
      #SWIFT_FLAGS: "-target x86_64-apple-macosx10.14" 
    steps: 
    #- name: Switch to MacOSX 10.15 SDK
    #  id: macossdk
    #  run: |
    #    curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.14.sdk.tar.xz
    #    tar -C $SDK_PATH -xf MacOSX10.14.sdk.tar.xz
    #    sudo rm -rf $SDK_PATH/MacOSX11.3.sdk
    #    sudo rm -rf $SDK_PATH/MacOSX.sdk
    #    sudo ln -s $SDK_PATH/MacOSX10.14.sdk $SDK_PATH/MacOSX.sdk
    #    sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.15" /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

    #- name: Install Swift 4.x toolchain
    #  id: swift4
    #  run: |
    #    #swift 4.x toolchain
    #    curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
    #    sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /
  
    - name: Switch to Xcode 11.7
      id: xcode117
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer   
   
    - name: Check
      run: |
        echo "xcode sdks===="
        ls /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
        echo "CommandLineTools sdks===="
        ls /Library/Developer/CommandLineTools/SDKs
        echo "show sdk path===="
        sudo xcrun --sdk macosx --show-sdk-path
        echo "toolchain swift version===="
        sudo xcrun --toolchain swift swift --version
        #export TOOLCHAINS=org.swift.42420190329a
        #echo "show org.swift.42420190329a version===="
        #sudo xcrun --toolchain swift swift --version
        echo "show MACOS_SDK_VERSION"
        sudo xcrun --sdk macosx -show-sdk-version
        echo "show clang path===="
        sudo xcrun --find clang
        echo "usr/bin/clang version====" 
        sudo /usr/bin/clang --version
        echo "CLTs clang version====" 
        sudo /Library/Developer/CommandLineTools/usr/bin/clang --version
   


