  
name: test

on:
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: windows-2022
    steps:   
    - name: Set path
      shell: cmd
      run: |
        set path=%PATH%;C:\Program Files\7-Zip
        echo CLEAN_PATH=%path% > %GITHUB_ENV%
        
    - name: Get current date and random hash
      run: |
        echo "random_hash=$(echo $RANDOM | md5sum | head -c 20)" >> $GITHUB_ENV
        
    - name: ls python lib
      run: |
        ls /c/hostedtoolcache/windows/python/3.7.9/x64/lib/pkgconfig        
        
    - name: Display the path
      run: echo ${env:PATH}                
        
    - uses: actions/checkout@v3
    - name: Install Nasm
      run: |
        curl -OL https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip 
        mkdir All-in-One
        cp test All-in-One
        7z x nasm* -o'All-in-One'
        7z a All-in-One.7z All-in-One/*

  test:
    runs-on: macos-12
    steps:    
      - name: Set path
        run: |
          echo $PATH

