  
name: test

on:
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: windows-2022
    steps:   
    - name: Set path
      shell: cmd
      run: |
        set path=%path%;C:\Program Files\7-Zip
        echo CLEAN_PATH=%path% > %GITHUB_ENV%
        
    - uses: actions/checkout@v3
    - name: Install Nasm
      run: |
        curl -OL https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip 
        mkdir mkdir All-in-One
        cp test All-in-One
        7z x nasm* -o'All-in-One'
        7z a All-in-One.7z All-in-One/*

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: All*.zip
