  
name: test

on:
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: windows-2022
    steps:   
    - name: Set path
      shell: cmd
      run: |
        echo %PATH%

        
    - name: Get current date and random hash
      run: |
        echo "random_hash=$(echo $RANDOM | md5sum | head -c 20)" >> $GITHUB_ENV         
   
    - name: Display the path
      run: echo ${env:PATH}                

    - uses: actions/checkout@v3
    - name: Install Nasm
      run: |
        curl -OL https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip 
        mkdir All-in-One
        cp test All-in-One
        7z x nasm* -o'All-in-One'
        7z a All-in-One.7z All-in-One/*

  macos-env:
    runs-on: macos-12
    steps:    
      - name: Set path
        run: |
          echo $PATH
          
  linux-env:
    runs-on: ubuntu-22.04
    steps:    
      - name: Set path
        run: |
          echo $PATH
          ls /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains

