  
name: test

on:
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: windows-2022
    steps:   
    - name: Set path
      shell: cmd
      run: |
        echo CLEAN_PATH=%path% > %GITHUB_ENV%
        
    - name: Install Nasm
      run: |
        curl -OL https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip 
        &'C:\Program Files\7-Zip\7z.exe' x nasm*.zip
        mv D:/a/test/test/nasm-2.15.05/nasm.exe "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC" 
