name: cygwin
defaults:
  run:
    shell: C:\cygwin\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Install cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        platform: x86_64
        install-dir: C:\cygwin
        packages: p7zip

    - name: Install GCC With MCF Toolchain
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-13.2.1-20231227-x64-ucrt.7z
        7z x target-gcc-mcf*.7z -o/cygdrive/d && mv /cygdrive/d/target /cygdrive/d/ucrt64
        #cp /cygdrive/c/Windows/System32/cmd.exe /d/ucrt64/bin
