name: find

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    steps:  
      - name: pwd
        run: |
          pwd
          mkdir test123
   
      - name: test
        run: |
          sudo find /usr -type d -name "zlib" -exec mv {} test123 \;
          ls test123/zlib
        
    
        
