name: find

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    steps:         
      - name: test
        run: |
          find /usr -type d -name "Cellar" -exec ls {} +
        
    
        
