name: sdk

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-11
    steps:   
    - name: show swift
      run: |
        echo "TOOLCHAINS ENV====="
        echo "$TOOLCHAINS"
        echo "find clang===="
        sudo xcrun --toolchain clang --find clang
        echo "find swift===="
        sudo xcrun --toolchain swift --find swift
        echo "toolchain swift version===="
        sudo xcrun --toolchain swift swift --version        
        echo "swift version===="
        sudo swift -v
    
    #- name: Install Swift 4.x toolchain
    #  id: swift4
    #  run: |
        # Swift 4.x toolchain
        #curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
        #sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /
        #TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-latest.xctoolchain/Info.plist)
        #echo "find swift===="
        #sudo xcrun --toolchain swift --find swift
        #echo "toolchain swift version===="
        #sudo xcrun --toolchain swift swift --version        
        #echo "TOOLCHAINS swift version===="
        #sudo xcrun --toolchain $TOOLCHAINS swift --version
    
    - name: Check
      run: |
        echo "xcode sdks======="
        ls /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
        echo "CommandLineTools sdks===="
        ls /Library/Developer/CommandLineTools/SDKs
        echo "XcodeDefault.xctoolchain===="
        ls /Applications/Xcode_12.5.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
        echo "show sdk version"
        xcrun --show-sdk-version
