name: path
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:  
      - name: users
        run: |
          cat /etc/passwd
          
      - name: github path
        run: |
          echo "path env=============="
          echo "$PATH"
          echo "/usr=============="
          ls /usr
          
