name: check-plutil

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-12
    #env:
      #SDKROOT: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"    
      #MACOS_SDK: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      #SDK_PATH: "/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
      #SWIFT_FLAGS: "-target x86_64-apple-macosx10.14" 
    steps: 
    - name: Install Swift 4.x toolchain
      id: swift4
      run: |
        #swift 4.x toolchain
        curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
        sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /
        
    - name: Check plutil function
      run: |
        TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-latest.xctoolchain/Info.plist)
        echo "$TOOLCHAINS"
