name: python

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-12
    steps:  
      - name: pwd
        run: |
          pwd
          mkdir test123 test456
   
      - name: test
        run: |
          ls */Library/Frameworks/Python.framework
        
    
        
