name: release

on:
  workflow_dispatch:
    
jobs:  
  build1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      CURL_RETRIES: "--connect-timeout 60 --retry 999 --retry-delay 5"
    steps:   
    - uses: actions/checkout@main
    - name: Release 1  
      shell: bash
      run: |
        echo "release_id=`curl -u $GITHUB_ACTOR:$GH_TOKEN $CURL_RETRIES \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases/tags/dev | jq '.id'`" >> $GITHUB_ENV                  
        curl -u $GITHUB_ACTOR:$GH_TOKEN $CURL_RETRIES \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id
