name: release

on:
  workflow_dispatch:
    
jobs:  
  build1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.BOT }}
      CURL_RETRIES: "--connect-timeout 60 --retry 999 --retry-delay 5"
    steps:   
    - uses: actions/checkout@main
    - name: Release 1  
      run: |
        id=$(curl -u ek5624:$GH_TOKEN $CURL_RETRIES -s -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/eko5624/test/releases -d '{"tag_name": "dev"}' | jq -r '.id')
        for f in vulkan-dev/*.zst; do curl -u eko5624:$GH_TOKEN $CURL_RETRIES -X POST -H "Accept: application/vnd.github.v3+json" -H "Content-Type: $(file -b --mime-type $f)" https://uploads.github.com/repos/eko5624/test/releases/81316560/assets?name=$(basename $f) --data-binary @$f; done
