name: release

on:
  workflow_dispatch:
    
jobs:  
  build1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      CURL_RETRIES: "--connect-timeout 60 --retry 999 --retry-delay 5"
    steps:   
    - uses: actions/checkout@main
    - name: Release 1  
      shell: bash
      run: |
        for f in vulkan-dev/*.zst; do 
          curl -u $GITHUB_ACTOR:$GH_TOKEN $CURL_RETRIES \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: $(file -b --mime-type $f)" \
            https://uploads.github.com/repos/${{ github.repository }}/releases/84926938/assets?name=$(basename $f) \
            --data-binary @$f; 
        done
