name: sh-test

on:
  workflow_dispatch:
    
jobs:  
  test:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
    - name: Test
      shell: msys2 {0}
      run: |
        file `cygpath -S`/vulkan-1.dll
        
