name: sh-test

on:
  workflow_dispatch:
    
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@main
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
        CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"     
      shell: bash 
      run: |
        chmod +x ./release-dev.sh
        ./release-dev.sh vulkan-dev vulkan-dev
