name: sh-test

on:
  workflow_dispatch:
    
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@main
    - name: Release    
      shell: bash 
      run: |
        chmod +x ./release-dev.sh
        ./release-dev.sh 'vulkan-dev' 'vulkan-dev'
