name: Executable flag setting

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: json test
      run: |
        chmod +x ./ver.sh
        ./ver.sh
