name: zip-test

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: zip
      run: |
        zip -r packages.zip packages/*
      
    - name: Upload binary packages
      uses: softprops/action-gh-release@master
      with:
        tag_name: test
        name: test-packages
        files: |
          packages.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
